#!/bin/sh

for DIC in "$(ls dic/)"; do
	mkdir -vp "dist/$DIC";
	tar -pczvf "dist/$DIC/stardict-$DIC.tar.gz" "dic/$DIC" "LICENSE";
	md5sum -b "dist/$DIC/stardict-$DIC.tar.gz" > "dist/$DIC/$DIC.md5";
done;
